### ISSUE TITLE
output?

### ISSUE THREAD

**Issue by Research2000** [nyu-dl/dl4mt-c2c#10]
Hi @jasonleeinf 
Thanks for sharing the code. Could you please tell me which line of your code is the output of your encoder? Thanks for your time and help.

**Comment by jaseleephd** [comment]
See [here](https://github.com/nyu-dl/dl4mt-c2c/blob/master/char2char/char_base.py#L120). `ctx` is the concatenation of the forward and backward GRU hidden states (its length is the number of segments in the source sentence + padding, see [the paper](https://arxiv.org/pdf/1610.03017v2.pdf), ctrl+F "segment" for clarification). `ctx` is passed to the main decoder function, `two_layer_gru_decoder`. `ctx_mean` is used as initial hidden states for both layers (hence `init_state_char ` and `init_state_word `) of the decoder.
