### ISSUE TITLE
Decode on CPU

### ISSUE THREAD

**Issue by dotjrt** [nyu-dl/dl4mt-c2c#11]
I was trying to pull down a trained model and test it out on a machine with no GPU (to avoid all the extra cost of cloud GPU machines) but I got an error:

Traceback (most recent call last):
  File "translate/translate_char2char.py", line 293, in <module>
    interactive=args.interactive,
  File "translate/translate_char2char.py", line 185, in main
    init_translation_model(model, options, init_params, build_sampler)
  File "translate/translate_char2char.py", line 40, in init_translation_model
    f_init, f_next = build_sampler(tparams, options, trng, use_noise)
  File "/home/jrthom18/data/char_model/dl4mt-c2c/char2char/char_base.py", line 187, in build_sampler
    conv_out = get_layer('multi_scale_conv_encoder')[1](tparams, emb, options, prefix='multi_scale_conv_enc1', width=options['conv_width'], nkernels=options['conv_nkernels'], pool_window=options['pool_window'], pool_stride=options['pool_stride'])
  File "/home/jrthom18/data/char_model/dl4mt-c2c/char2char/mixer.py", line 487, in multi_scale_conv_encoder
    output.append(dnn_conv(data, W[idx], border_mode='half', precision='float32'))
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn.py", line 1160, in dnn_conv
    return GpuDnnConv(algo=algo)(img, kerns, out, desc)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn.py", line 328, in __init__
    if version() < (3000, 3000):
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.py", line 407, in dnn_version
    dnn_available.msg)
Exception: ("We can't determine the cudnn version as it is not available", 'CUDA not available')

This was after I had tried setting the Theano `device` flag to `cpu`. Is there a quick way around this?

**Comment by jaseleephd** [comment]
Unfortunately `translate*.py` in my repo only supports GPU-decoding. [Here](https://github.com/nyu-dl/dl4mt-cdec/blob/master/character_base/translate.py) is a multithreaded CPU-based decoding script for [dl4mt-cdec](https://github.com/nyu-dl/dl4mt-cdec), it's compatible with my project. You should be able to take the models from `dl4mt-c2c` and decode using that script. See [here](https://github.com/nyu-dl/dl4mt-cdec/blob/master/translate_readme.txt) for some sample commands to use that script.

**Comment by jaseleephd** [comment]
Actually, on second thought, that script defines some other model altogether. It wouldn't work on `dl4mt-c2c` models.

Sorry about this. The trouble is, my convolutions are `dnn_conv`, which is GPU-only. If you want to decode on CPUs, you'll have to replace the `dnn_conv` with `conv2d` (the arguments should roughly be the same) in `build_sampler` in `char_base.py`. You wouldn't need to train a new model though. You could take my pre-trained models (trained on GPUs) and decode on CPUs.

**Comment by jaseleephd** [comment]
Let me know if you manage to fix this.

**Comment by dotjrt** [comment]
It looks like `dnn_conv` is being invoked in `mixer.py` ... would that be where it needs to be replaced with `conv2d`?

**Comment by dotjrt** [comment]
Got it. Using `conv2d` instead of `dnn_conv` and then `pool_2d` instead of `dnn_pool` in `mixer.py` did the trick. Thanks!

**Comment by jaseleephd** [comment]
Yes that's spot on. Glad it worked!
