### ISSUE TITLE
Using custom datasets

### ISSUE THREAD

**Issue by stefan-it** [nyu-dl/dl4mt-c2c#12]
Hi,

thanks for your sharing the code! I've some question about the `preprocess/build_dictionary_char.py` script.

* Can you provide some example program options? Currently the `main` method is never called.

* The `main` method comes with three arguments, what exactly is expected for `short_list` and `src`?

I would really like to document all steps which are necessary to preprocess custom datasets (I would extend the documention later) :)

**Comment by jaseleephd** [comment]
Hi! What I normally do is: first, open iPython
1. `from build_dictionary_char import main`
2. `main("file.txt", 300, True)`

`short_list` is the size of the vocabulary
`src` is a boolean (True for source vocab, False for target vocab)
