### ISSUE TITLE
Possible bug in `*/nmt[_many].py`

### ISSUE THREAD

**Issue by fsxfreak** [nyu-dl/dl4mt-c2c#15]
At this line,
https://github.com/nyu-dl/dl4mt-c2c/blob/360fb6680826e0bfc38a6c5933db37e88c0e3ef6/bpe2char/nmt_many.py#L197

`re_load_old_setting` has no effect, because `models_options` is never referenced again. Should this be `model_options`?

**Comment by kyunghyuncho** [comment]
indeed this seems to be a bug which however wouldn't have affected too much as long as the command line options were kept as they were during training. i'll let @jasonleeinf answer in more detail.

**Comment by jaseleephd** [comment]
This is indeed a typo, my bad. Thanks a lot for letting us know! Just fixed this.
