### ISSUE TITLE
Per-instance weighted loss

### ISSUE THREAD

**Issue by nzhiltsov** [nyu-dl/dl4mt-c2c#16]
Hi,

could you please help me: I'd like to add weighting for each seq2seq pair (aka weighted loss). How can I do that?

I realize that 'cost' function should be multiplied by the weight vector from 'prepare_data' before 'mean'. But failed to accomplish it in this code.

Thanks in advance!

**Comment by kyunghyuncho** [comment]
what you need to do is to initialize a mask vector as a theano tensor at the beginning of ``build_model``, multiply it to ``cost`` at the end, return it and include it in ``inps``. whenever you call ``f_grad_shared`` or ``f_log_probs``, you should then pass the mask returned from ``prepare_data``.

**Comment by nzhiltsov** [comment]
Thanks! Will try that.

**Comment by nzhiltsov** [comment]
It's me again. I've done with it: https://github.com/nzhiltsov/dl4mt-c2c/tree/spellcheck

Run a tiny setup:
> python char2char/train_bi_char2char.py -task spellcheck -translate src_tgt -enc_d
im 32 -dec_dim 32  -batch_size 8 -highway 1 -conv_width 1-2-3 -conv_nkernels 200-200-250

But got the following error:

> Traceback (most recent call last):                                                                                     [66/1807]
  File "char2char/train_bi_char2char.py", line 169, in <module>
    main(0, args)
  File "char2char/train_bi_char2char.py", line 88, in main
    prepare_data=prepare_data,
  File "/home/nzhiltsov/distr/dl4mt-c2c/char2char/nmt.py", line 393, in train
    cost, not_finite, clipped = f_grad_shared(x, x_mask, y, y_mask, cost_mask)
  File "/home/nzhiltsov/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/nzhiltsov/anaconda2/lib/python2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/nzhiltsov/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: Input dimension mis-match. (input[0].shape[0] = 8, input[2].shape[0] = 92)

Could you please comment on it: what's wrong with it?

**Comment by jaseleephd** [comment]
Looks like dimensions are not compatible somewhere. Does `input[0].shape[0] = 8, input[2].shape[0] = 92` ring any bell?

**Comment by nzhiltsov** [comment]
My guess is that the error comes out here: https://github.com/nzhiltsov/dl4mt-c2c/blob/spellcheck/char2char/char_base.py#L175

not sure, what the shape of cost_mask shoud be then (now it's _(1, batch_size)_ )

**Comment by nzhiltsov** [comment]
Yes, indeed with _optimizer=None_ Theano shows a clear stacktrace:

> ValueError: Input dimension mis-match. (input[0].shape[0] = 92, input[1].shape[0] = 1)
> Apply node that caused the error: Elemwise{mul,no_inplace}(Elemwise{mul,no_inplace}.0, cost_mask)
> Toposort index: 1212
> Inputs types: [TensorType(float32, matrix), TensorType(float32, matrix)]
> Inputs shapes: [(92, 8), (1, 8)]
> Inputs strides: [(32, 4), (32, 4)]
> Inputs values: ['not shown', 'not shown']
> Outputs clients: [[Sum{axis=[0], acc_dtype=float64}(Elemwise{mul,no_inplace}.0), Elemwise{second}(Elemwise{mul,no_inplace}.0, Di
> mShuffle{x,0}.0)]]
> 
> Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
>   File "char2char/train_bi_char2char.py", line 169, in <module>
>     main(0, args)
>   File "char2char/train_bi_char2char.py", line 88, in main
>     prepare_data=prepare_data,
>   File "/home/nzhiltsov/distr/dl4mt-c2c/char2char/nmt.py", line 237, in train
>     build_model(tparams, model_options)
>   File "/home/nzhiltsov/distr/dl4mt-c2c/char2char/char_base.py", line 175, in build_model
>     cost = (cost * y_mask * cost_mask).sum(0)

**Comment by nzhiltsov** [comment]
Looks like 

> cost = (cost * y_mask * cost_mask).sum(0)

should be

> cost = (cost * y_mask).sum(0)
> cost = cost * cost_mask

right?
