### ISSUE TITLE
What is  wmts in the code?

### ISSUE THREAD

**Issue by ghost** [nyu-dl/dl4mt-c2c#19]
in train_bi_char2char.py:

def main(job_id, args):
    save_file_name = args.model_name
    source_dataset = args.data_path + wmts[args.translate]['train'][0][0]
    target_dataset = args.data_path + wmts[args.translate]['train'][0][1]
    valid_source_dataset = args.data_path + wmts[args.translate]['dev'][0][0]
    valid_target_dataset = args.data_path + wmts[args.translate]['dev'][0][1]
    source_dictionary = args.data_path + wmts[args.translate]['dic'][0][0]
    target_dictionary = args.data_path + wmts[args.translate]['dic'][0][1]

what is wmts? where is it created?

**Comment by jaseleephd** [comment]
line 6 : from wmt_path import *

**Comment by berzentine** [comment]
wmt_path error!     from wmt_path import *
ImportError: No module named wmt_path
