### ISSUE TITLE
One question about highway

### ISSUE THREAD

**Issue by puzzledTao** [nyu-dl/dl4mt-c2c#22]
Hello, I have read your paper. The segment embedding is fed into the highways in your paper. And I found 
the definition of hwlayer in char2char/mixer.py.  However, I do not find where the function is called? Can you tell me this? Thakn you

**Comment by jaseleephd** [comment]
https://github.com/nyu-dl/dl4mt-c2c/blob/708a84507984104e37367eacef16016dd72133ff/char2char/char_base.py#L28
