### ISSUE TITLE
Preprocessing for other datasets

### ISSUE THREAD

**Issue by qingyuanxingsi** [nyu-dl/dl4mt-c2c#4]
Much thanks for sharing your code.
If I want to use the model for other datasets, do I need to perform the punctuation-normalization and tokenization step as present in the preprocess.sh script.
For example, "translating" a char sequence to another char sequence(**the char sequences may not be actual natural language sentences!**)

**Comment by jaseleephd** [comment]
Hey @qingyuanxingsi, the answer is no, you don't have to perform any preprocessing for the char2char model. We only did it for comparison purposes with the other bpe2char models, but the char2char model does not need any preprocessing.
