### ISSUE TITLE
Why save the best model only when saveFreq != validFreq ?

### ISSUE THREAD

**Issue by hitochan777** [nyu-dl/dl4mt-c2c#5]
Hi~ Thank you for your great work!
I have a question regarding [line 613](https://github.com/nyu-dl/dl4mt-c2c/blob/master/char2char/nmt.py#L613) in `char2char/nmt.py`.
It seems that your code saves the best model when `saveFreq != validFreq`, but 
by default `saveFreq` and `validFreq` are both set to 5000, which means that by default
the best model is not saved. Is there any reason why you don't save the best model when they are
the same?

**Comment by jaseleephd** [comment]
Hi @hitochan777 

Please see [line 569](https://github.com/nyu-dl/dl4mt-c2c/blob/master/char2char/nmt.py#L569).  This is where the best model is saved. Note that [line 613](https://github.com/nyu-dl/dl4mt-c2c/blob/master/char2char/nmt.py#L613) (and [line 542](https://github.com/nyu-dl/dl4mt-c2c/blob/master/char2char/nmt.py#L542) for that matter) is where we validate the model, here we check if the validated model hasn't been saved already with `saveFreq != validFreq`, and only save it if we haven't already.

Hope that helped.

Jason

**Comment by hitochan777** [comment]
Hi @jasonleeinf 

Ok, thanks.
I guess [line 569](https://github.com/nyu-dl/dl4mt-c2c/blob/master/char2char/nmt.py#L569) saves the model regardless of whether or not it gives the best validation score. Maybe I misunderstand your code, but it is very likely that the saved model at [last](https://github.com/nyu-dl/dl4mt-c2c/blob/master/char2char/nmt.py#L611) does not give you the best model. But basically I should use the model which gives the best validation score, right?

**Comment by jaseleephd** [comment]
Yes, of course. By the way the validation score computed here is log likelihood. Ultimately you want the model that gives the best validation **BLEU** score. Please use `translate/translate_char2char.py` to decode validation datasets with the saved models, compute BLEU score using `preprocess/multi-bleu.perl`, then choose the model that gives the highest BLEU.

**Comment by hitochan777** [comment]
Ah I see. Thank you for your explanation.
By the way, it would be nice if I can save the model with the highest validation BLEU score during training, because it is a bit annoying to decode validation datasets and compute the BLEU score for every single model under the model path after training.

Anyways, thanks!

**Comment by jaseleephd** [comment]
Yeah I agree. I wrote a separate script to decode & compute BLEU scores automatically, but didn't put this in the repo.

**Comment by hitochan777** [comment]
@jasonleeinf OK. Thanks for your help! I will close this issue.
