### ISSUE TITLE
Adapting for neural conversational model?

### ISSUE THREAD

**Issue by dotjrt** [nyu-dl/dl4mt-c2c#7]
Can this model be easily adapted to work as a neural conversational mode (i.e. https://arxiv.org/abs/1506.05869)? Effectively not translating from one language to another but instead from utterances of one language into responses of that same language?

**Comment by jaseleephd** [comment]
Certainly! Get your hands on some training data (Looks like you can get some from [here](https://github.com/nicolas-ivanov/seq2seq_chatbot_links) or [here](https://people.mpi-sws.org/~cristian/Cornell_Movie-Dialogs_Corpus.html)), run `build_dictionary_char.py` on it to learn the vocabulary (here the source and target vocabularies would be the same), start training and there you go. your character-level conversational model.

**Comment by dotjrt** [comment]
Thanks for the help. Great work on this project!

**Comment by jaseleephd** [comment]
Cheers!
