### ISSUE TITLE
Training-Question

### ISSUE THREAD

**Issue by Brice4** [nyu-dl/dl4mt-c2c#9]
Hi @jasonleeinf
Thanks for your code and congratulations to your paper. I got an error during training!

/home/dl4mt-c2c-master/char2char/nmt.py(407)train()

could you please help me?

**Comment by jaseleephd** [comment]
You're getting NaNs. Have you changed any hyperparameters regarding convolutions, e.g. width of filters, pooling width, etc? 

Also, did you learn your own vocabulary or use provided ones from WMT?

**Comment by SMRN** [comment]
No, i didn't do that. i used your recommended dataset (WMT).

**Comment by SMRN** [comment]
Sorry. that's my fault:)
